/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'
import { Route as StudyQuizIdRouteImport } from './routes/study/quiz/$id'
import { Route as StudyFlashcardIdRouteImport } from './routes/study/flashcard/$id'
import { Route as ClassTeacherClassIdRouteImport } from './routes/class/teacher/$classId'
import { Route as ClassStudentClassIdRouteImport } from './routes/class/student/$classId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyQuizIdRoute = StudyQuizIdRouteImport.update({
  id: '/study/quiz/$id',
  path: '/study/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyFlashcardIdRoute = StudyFlashcardIdRouteImport.update({
  id: '/study/flashcard/$id',
  path: '/study/flashcard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassTeacherClassIdRoute = ClassTeacherClassIdRouteImport.update({
  id: '/class/teacher/$classId',
  path: '/class/teacher/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassStudentClassIdRoute = ClassStudentClassIdRouteImport.update({
  id: '/class/student/$classId',
  path: '/class/student/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/class/student/$classId': typeof ClassStudentClassIdRoute
  '/class/teacher/$classId': typeof ClassTeacherClassIdRoute
  '/study/flashcard/$id': typeof StudyFlashcardIdRoute
  '/study/quiz/$id': typeof StudyQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/class/student/$classId': typeof ClassStudentClassIdRoute
  '/class/teacher/$classId': typeof ClassTeacherClassIdRoute
  '/study/flashcard/$id': typeof StudyFlashcardIdRoute
  '/study/quiz/$id': typeof StudyQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/class/student/$classId': typeof ClassStudentClassIdRoute
  '/class/teacher/$classId': typeof ClassTeacherClassIdRoute
  '/study/flashcard/$id': typeof StudyFlashcardIdRoute
  '/study/quiz/$id': typeof StudyQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/history'
    | '/login'
    | '/profile'
    | '/category/$categoryId'
    | '/class/student/$classId'
    | '/class/teacher/$classId'
    | '/study/flashcard/$id'
    | '/study/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/history'
    | '/login'
    | '/profile'
    | '/category/$categoryId'
    | '/class/student/$classId'
    | '/class/teacher/$classId'
    | '/study/flashcard/$id'
    | '/study/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/history'
    | '/login'
    | '/profile'
    | '/category/$categoryId'
    | '/class/student/$classId'
    | '/class/teacher/$classId'
    | '/study/flashcard/$id'
    | '/study/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ClassStudentClassIdRoute: typeof ClassStudentClassIdRoute
  ClassTeacherClassIdRoute: typeof ClassTeacherClassIdRoute
  StudyFlashcardIdRoute: typeof StudyFlashcardIdRoute
  StudyQuizIdRoute: typeof StudyQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/quiz/$id': {
      id: '/study/quiz/$id'
      path: '/study/quiz/$id'
      fullPath: '/study/quiz/$id'
      preLoaderRoute: typeof StudyQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/flashcard/$id': {
      id: '/study/flashcard/$id'
      path: '/study/flashcard/$id'
      fullPath: '/study/flashcard/$id'
      preLoaderRoute: typeof StudyFlashcardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/teacher/$classId': {
      id: '/class/teacher/$classId'
      path: '/class/teacher/$classId'
      fullPath: '/class/teacher/$classId'
      preLoaderRoute: typeof ClassTeacherClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/student/$classId': {
      id: '/class/student/$classId'
      path: '/class/student/$classId'
      fullPath: '/class/student/$classId'
      preLoaderRoute: typeof ClassStudentClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ClassStudentClassIdRoute: ClassStudentClassIdRoute,
  ClassTeacherClassIdRoute: ClassTeacherClassIdRoute,
  StudyFlashcardIdRoute: StudyFlashcardIdRoute,
  StudyQuizIdRoute: StudyQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
